### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AndreyBaglai** [AndreyBaglai/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by mustang-eleanor** [comment]
**TIMELINE**

1.Torokhtiy was born on May 22, 1986 in Zugres, Donetsk region, Ukraine.
2.In 2003 he graduated from Kharkiv Regional Higher School of Physical Culture with a degree in Physical Education.
3.In 2010 he graduated from Kharkiv Aviation Institute with a major in "Control system for flying machines and complexes" and was certified as an engineer.
4.In 2014 he received a second degree in Zaporizhzhya National University, specializing in physical education and sports / weightlifting coach.
5.In 2016, he founded the international brand of sportswear and accessories "Warm Body Cold Mind" (WBCM). It became famous for its slogan on t-shirts. "The (WBCM) shirt made its debut in (famous American baseball player Bryce Harper) his first media address in Florida, and was casually noted by the Washington Post, ESPN, Yahoo! Sports and more, who failed to grasp what it means". As well Oleksiy Torokhtiy launched an online weightlifting program Torwod
