### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by AndreyBaglai** [AndreyBaglai/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by mustang-eleanor** [comment]
**OLEKSIY TOROKHTIY**

[https://www.youtube.com/user/WeightliftingUkraine](https://www.youtube.com/user/WeightliftingUkraine)
[https://www.instagram.com/torokhtiy/](https://www.instagram.com/torokhtiy/)
[https://www.facebook.com/Torokhtiyo/](https://www.facebook.com/Torokhtiyo/)
