### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AndreyBaglai** [AndreyBaglai/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by mustang-eleanor** [comment]
Oleksiy Pavlovych Torokhtiy (Ukrainian: Олексій Павлович Торохтій; born May 22, 1986 in Zuhres) is a Ukrainian weightlifter, an Olympic Gold Medalist in weightlifting (London 2012) until disqualified for a doping offence, winner of World and European Championships. Participant of two Olympic Games (2008, 2012). Oleksiy is also a Member of European Weightlifting Federation Executive Committee, Deputy Chairman of Ukrainian National Olympic Commіttee Athletes Commission and the Vice-President of the Weightlifting Federation of Ukraine.
